package programe;

import java.util.Random;

public class Muthuzoho {

	public static void main(String[] args) {
				// Data storage
				// input data collection
				// Finding the sum
				// Finding top 10
				// Stock management
				// Projected sale
				// Manufacturing process
				TextileCompany myCompany = new TextileCompany();
				myCompany.inputData();
				myCompany.printProductsAndSaleInfo();
				
				myCompany.computeSaleSummary();
				myCompany.printSummaryData();
				
				//int[] toppers = TextileUtil.computeTopN(10, summaryData);

	}

}
class TextileCompany{
	int productSize = 100;
	int daysCount = 10;
	String[] products = new String[productSize];
	//int[][][] saleInfo = new int[daysCount][productSize][productSize];
	int[][] saleInfo = new int[daysCount][productSize];
	int[] stockData = new int[productSize];
	int[] summaryData;
	
	public void inputData() {
//		String myFirstProduct = "Hooded tshirts";
//		int saleCountForDay1 = 100;
		
		products[0] = "Hooded tshirts";
		saleInfo[0][0] = 100;
		saleInfo[1][0] = 500;
		Random randomGenerator = new Random();
		//autogenerated product name
		for(int currentProductNo = 1 ; currentProductNo < productSize ; currentProductNo++) {
			
			products[currentProductNo] = String.valueOf(randomGenerator.longs(10000, 99999));
			
			for(int currentDay = 0 ; currentDay < daysCount ; currentDay++) {
				saleInfo[currentDay][currentProductNo] = randomGenerator.nextInt(600);
			}
		}
		
	}

	public void printSummaryData() {
		// product size first add pannanum ella productskum.
		// product summery enna nu print pannanum product name and salesinfo venum.
		
		
		for(int products=1;products<=productSize;products++) {
			
			
			
		}
		
		 
		
		
	}

	public void computeSaleSummary() {
		
		int[] productSummary = new int[productSize];
		
		for(int currentDay = 0; currentDay < saleInfo.length; currentDay++) {
			for (int currentProduct : saleInfo[currentDay]) {
				productSummary[currentProduct] += saleInfo[currentDay][productSize];
				
			}
			
		}
		
		summaryData = productSummary; 
		
	}
	
	public void printProductsAndSaleInfo() {
		for (int productNo = 0 ; productNo < productSize ; productNo++) {
			System.out.println("Product "+productNo+": "+products[productNo]);
			
			for(int currentDay = 0 ; currentDay < daysCount ; currentDay++) {
				System.out.print("Sale day: "+ currentDay + " SaleCount: "+ saleInfo[currentDay][productNo] + " " );
			}
			System.out.println();
		}
	}
}

class TextileUtil{
	public static int[] computeTopN( int number, int[] data) {
		int[] topElements = new int[number];
		
		return topElements;
	}
}                                                                                                         

